// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'health.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Health _$HealthFromJson(Map<String, dynamic> json) {
  return Health(
    address: json['address'] as String,
    approveTime: json['approveTime'] as String,
    checkPersonType: json['checkPersonType'] as String,
    checkResult: json['checkResult'] as String,
    checkType: json['checkType'] as String,
    city: json['city'] as String,
    cityName: json['cityName'] as String,
    classId: json['classId'] as String,
    className: json['className'] as String,
    confirmTime: json['confirmTime'] as String,
    county: json['county'] as String,
    countyName: json['countyName'] as String,
    createOrgId: json['createOrgId'] as String,
    createUserId: json['createUserId'] as String,
    department: json['department'] as String,
    departmentName: json['departmentName'] as String,
    discomfortDesp: json['discomfortDesp'] as String,
    division: json['division'] as String,
    divisionName: json['divisionName'] as String,
    gender: json['gender'] as String,
    grade: json['grade'] as String,
    gradeName: json['gradeName'] as String,
    heaId: json['heaId'] as String,
    id: json['id'] as String,
    ids: (json['ids'] as List)?.map((e) => e as String)?.toList(),
    illStatus: json['illStatus'] as String,
    isContactSuspect: json['isContactSuspect'] as String,
    isDiscomfort: json['isDiscomfort'] as String,
    isDiscomfortHome: json['isDiscomfortHome'] as String,
    isDiscomfortPart: json['isDiscomfortPart'] as String,
    isQuarantine: json['isQuarantine'] as String,
    jobNum: json['jobNum'] as String,
    name: json['name'] as String,
    personType: json['personType'] as String,
    phone: json['phone'] as String,
    province: json['province'] as String,
    provinceName: json['provinceName'] as String,
    reportTime: json['reportTime'] as String,
    schoolName: json['schoolName'] as String,
    stuNum: json['stuNum'] as String,
    healDate: json['healDate'] as String,
    healHospital: json['healHospital'] as String,
    illDate: json['illDate'] as String,
    illType: json['illType'] as String,
    isHealed: json['isHealed'] as String,
    leaveDate: json['leaveDate'] as String,
    memo: json['memo'] as String,
    type: json['type'] as String,
    measure: json['measure'] as String,
    hurtSite: json['hurtSite'] as String,
    hurtSiteValue: json['hurtSiteValue'] as String,
    stuNumValue: json['stuNumValue'] as String,
    symptomType: json['symptomType'] as String,
    symptomTypeValue: json['symptomTypeValue'] as String,
  );
}

Map<String, dynamic> _$HealthToJson(Health instance) => <String, dynamic>{
      'address': instance.address,
      'approveTime': instance.approveTime,
      'checkPersonType': instance.checkPersonType,
      'checkResult': instance.checkResult,
      'checkType': instance.checkType,
      'city': instance.city,
      'cityName': instance.cityName,
      'classId': instance.classId,
      'className': instance.className,
      'confirmTime': instance.confirmTime,
      'county': instance.county,
      'countyName': instance.countyName,
      'createOrgId': instance.createOrgId,
      'createUserId': instance.createUserId,
      'department': instance.department,
      'departmentName': instance.departmentName,
      'discomfortDesp': instance.discomfortDesp,
      'division': instance.division,
      'divisionName': instance.divisionName,
      'gender': instance.gender,
      'grade': instance.grade,
      'gradeName': instance.gradeName,
      'heaId': instance.heaId,
      'id': instance.id,
      'ids': instance.ids,
      'illStatus': instance.illStatus,
      'isContactSuspect': instance.isContactSuspect,
      'isDiscomfort': instance.isDiscomfort,
      'isDiscomfortHome': instance.isDiscomfortHome,
      'isDiscomfortPart': instance.isDiscomfortPart,
      'isQuarantine': instance.isQuarantine,
      'jobNum': instance.jobNum,
      'name': instance.name,
      'personType': instance.personType,
      'phone': instance.phone,
      'province': instance.province,
      'provinceName': instance.provinceName,
      'reportTime': instance.reportTime,
      'schoolName': instance.schoolName,
      'stuNum': instance.stuNum,
      'illDate': instance.illDate,
      'illType': instance.illType,
      'isHealed': instance.isHealed,
      'healDate': instance.healDate,
      'healHospital': instance.healHospital,
      'memo': instance.memo,
      'type': instance.type,
      'leaveDate': instance.leaveDate,
      'measure': instance.measure,
      'hurtSite': instance.hurtSite,
      'hurtSiteValue': instance.hurtSiteValue,
      'stuNumValue': instance.stuNumValue,
      'symptomType': instance.symptomType,
      'symptomTypeValue': instance.symptomTypeValue,
    };
